tavy315_sylius_orders_admin_api_customer_order:
    resource: |
        alias: tavy315_sylius_orders.customer_order
        criteria:
            customer: $customer
        form: Tavy315\SyliusOrdersPlugin\Form\Type\CustomerOrderType
        grid: tavy315_sylius_orders_admin_customer_order
        identifier: documentNo
        only: [create, delete, update]
        path: 'customers/{customer}/orders'
        section: admin_api
        serialization_version: $version
        vars:
            route:
                parameters:
                    customer: $customer
                    documentNo: $documentNo
    type: sylius.resource_api

tavy315_sylius_orders_admin_api_customer_order_delete:
    path: /customers/{customer}/orders/{documentNo}
    methods: [ DELETE ]
    defaults:
        _controller: "tavy315_sylius_orders.controller.customer_order::deleteAction"
        _sylius:
            csrf_protection: false
            repository:
                method: findOneByCustomerAndDocument
                arguments:
                    - expr:service('sylius.repository.customer').findOneById($customer)
                    - $documentNo

tavy315_sylius_orders_admin_api_customer_order_update:
    path: /customers/{customer}/orders/{documentNo}
    methods: [ PATCH, PUT ]
    defaults:
        _controller: "tavy315_sylius_orders.controller.customer_order::updateAction"
        _sylius:
            criteria:
                customer: $customer
                documentNo: $documentNo
            form: Tavy315\SyliusOrdersPlugin\Form\Type\CustomerOrderType
            permission: false
            repository:
                method: findOneByCustomerAndDocument
                arguments:
                    - expr:service('sylius.repository.customer').findOneById($customer)
                    - $documentNo
            serialization_groups: [ Default, Detailed ]
            serialization_version: $version
